
const industryCodeMap = {
    gold_mine: 0,
    // bank: 1,
    tourists_centre: 2,
    water_supply: 3,
    factory: 4,
    chemical_plant: 5,
    oil_well: 6,
    // oil_rig: 7,
    oil_refinery: 8,
    plastic_plant: 9,
    forest: 10,
    sawmill: 11,
    paper_mill: 12,
    printing_works: 13,
    furniture_factory: 14,
    iron_ore_mine: 15,
    steel_mill: 16,
    vehicles_factory: 17,
    shipyard: 18,
    bauxite_mine: 19,
    aluminium_plant: 20,
    coal_mine: 21,
    power_station: 22,
    sand_pit: 23,
    glass_works: 24,
    cement_works: 25,
    brick_works: 26,
    lime_quarry: 27,
    cement_works: 28,
    construction_industry: 29,
    brick_works: 30,
    large_construction_industry: 31,
    fishing_grounds: 32,
    farm: 33,
    animal_farm: 34,
    tinning_factory: 35,
    textile_mill: 36,
    fruit_plantation: 37,
    brewery: 38,
    food_processing_plant: 39,
    national_bank: 40,
    petrol_station: 41,
    vehicle_saloon: 42,
    cargo_store: 43,
    water_tower: 44,
}

module.exports = industryCodeMap
