
const industryCodeMap = {
    gold_mine: 0,
    // bank: 1,
    tourists_centre: 2,
    water_supply: 3,
    factory: 4,
    fishing_boat: 5,
    farm: 6,
    animal_farm: 7,
    tinning_factory: 35,
    textile_mill: 9,
    fruit_plantation: 10,
    brewery: 11,
    food_processing_plant: 12,
    coal_mine: 13,
    power_station: 14,
    sand_pit: 15,
    glass_works: 16,
    cement_works: 17,
    brick_works: 18,
    chemical_plant: 19,
    oil_well: 20,
    // oil_rig: 21
    oil_refinery: 22,
    plastic_plant: 23,
    lime_quarry: 24,
    // cement_works: 25,
    construction_industry: 26,
    // brick_works: 27,
    large_construction_industry: 28,
    iron_ore_mine: 29,
    steel_mill: 30,
    vehicles_factory: 31,
    shipyard: 32,
    bauxite_mine: 33,
    aluminium_plant: 34,
    forest: 35,
    sawmill: 36,
    paper_mill: 37,
    printing_works: 38,
    furniture_factory: 39,
    // national_bank: 40
    petrol_station: 41,
    vehicle_saloon: 42,
    cargo_store: 43,
    water_tower: 44,
}

module.exports = industryCodeMap
